jobs:
  build:
    docker:
      - image: kivy/buildozer

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - buildozer-home-{{ checksum "buildozer.spec" }}
            # fallback to using the latest cache if no exact match is found
            - buildozer-home-

      - run:
          name: build
          command: |
            yes | buildozer android debug || echo "done"

      - save_cache:
          paths:
            - .buildozer
            - ~/.buildozer
          key: buildozer-home-{{ checksum "buildozer.spec" }}

      - store_artifacts:
          path: bin/
          destination: bin/

  publish-github-release:
    docker:
      - image: cibuilds/github:latest

    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(git describe --tag)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/

      - publish-github-release:
          requires:
            - build

          filters:
            branches:
              ignore: /.*/

            tags:
              only: /^v\d+\.\d+\.\d+$/
